[package]
name = "boruix_process"
version = "0.1.0"
edition = "2021"

[lib]
name = "boruix_process"
crate-type = ["staticlib"]

[dependencies]
heapless = "0.8"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = 3

[profile.dev]
panic = "abort"
