name: Build Boruix OS (x86_64)

# 在push和pull request时触发构建
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# 允许手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 安装构建依赖
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          nasm \
          gcc \
          binutils \
          grub-common \
          grub-pc-bin \
          xorriso \
          mtools
    
    # 构建x86_64架构
    - name: Build x86_64
      run: |
        echo "Building for architecture: x86_64"
        make clean
        make all
    
    # 压缩build目录
    - name: Compress build directory
      run: |
        cd build
        zip -r ../build_x86_64.zip .
        cd ..
        ls -la build_x86_64.zip
    
    # 上传构建产物
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: boruix-build-x86_64
        path: build_x86_64.zip
        retention-days: 30
    
    # 上传ISO文件
    - name: Upload ISO files
      uses: actions/upload-artifact@v4
      with:
        name: boruix-iso-x86_64
        path: build/x86_64/*.iso
        retention-days: 30
      continue-on-error: true
    
    # 显示构建信息
    - name: Display build info
      run: |
        echo "=== Build Summary for x86_64 ==="
        echo "Architecture: x86_64"
        echo "Build directory contents:"
        ls -la build/x86_64/ || echo "No build directory found"
        echo "ISO files:"
        ls -la build/x86_64/*.iso || echo "No ISO files found"
        echo "Compressed build size:"
        ls -lh build_x86_64.zip || echo "No compressed file found"
        echo "Build completed successfully!"